/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedMaintenanceRecordsRouteRouteImport } from './routes/_authed/maintenance-records/route'
import { Route as AuthedAssetsIndexRouteImport } from './routes/_authed/assets/index'
import { Route as AuthedAssetsLiveRouteImport } from './routes/_authed/assets/live'
import { Route as AuthedAssetsNewRouteImport } from './routes/_authed/assets/new'
import { Route as AuthedMaintenanceRecordsIndexRouteImport } from './routes/_authed/maintenance-records/index'
import { Route as AuthedMaintenanceRecordsNewRouteImport } from './routes/_authed/maintenance-records/new'
import { Route as AuthedAssetsIdEditRouteImport } from './routes/_authed/assets/$id.edit'
import { Route as AuthedMaintenanceRecordsIdEditRouteImport } from './routes/_authed/maintenance-records/$id.edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRecordsRouteRoute =
  AuthedMaintenanceRecordsRouteRouteImport.update({
    id: '/maintenance-records',
    path: '/maintenance-records',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAssetsIndexRoute = AuthedAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssetsLiveRoute = AuthedAssetsLiveRouteImport.update({
  id: '/assets/live',
  path: '/assets/live',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssetsNewRoute = AuthedAssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRecordsIndexRoute =
  AuthedMaintenanceRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedMaintenanceRecordsRouteRoute,
  } as any)
const AuthedMaintenanceRecordsNewRoute =
  AuthedMaintenanceRecordsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedMaintenanceRecordsRouteRoute,
  } as any)
const AuthedAssetsIdEditRoute = AuthedAssetsIdEditRouteImport.update({
  id: '/assets/$id/edit',
  path: '/assets/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRecordsIdEditRoute =
  AuthedMaintenanceRecordsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedMaintenanceRecordsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/maintenance-records': typeof AuthedMaintenanceRecordsRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/assets/live': typeof AuthedAssetsLiveRoute
  '/assets/new': typeof AuthedAssetsNewRoute
  '/maintenance-records/new': typeof AuthedMaintenanceRecordsNewRoute
  '/assets/': typeof AuthedAssetsIndexRoute
  '/maintenance-records/': typeof AuthedMaintenanceRecordsIndexRoute
  '/assets/$id/edit': typeof AuthedAssetsIdEditRoute
  '/maintenance-records/$id/edit': typeof AuthedMaintenanceRecordsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/': typeof AuthedIndexRoute
  '/assets/live': typeof AuthedAssetsLiveRoute
  '/assets/new': typeof AuthedAssetsNewRoute
  '/maintenance-records/new': typeof AuthedMaintenanceRecordsNewRoute
  '/assets': typeof AuthedAssetsIndexRoute
  '/maintenance-records': typeof AuthedMaintenanceRecordsIndexRoute
  '/assets/$id/edit': typeof AuthedAssetsIdEditRoute
  '/maintenance-records/$id/edit': typeof AuthedMaintenanceRecordsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/maintenance-records': typeof AuthedMaintenanceRecordsRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/assets/live': typeof AuthedAssetsLiveRoute
  '/_authed/assets/new': typeof AuthedAssetsNewRoute
  '/_authed/maintenance-records/new': typeof AuthedMaintenanceRecordsNewRoute
  '/_authed/assets/': typeof AuthedAssetsIndexRoute
  '/_authed/maintenance-records/': typeof AuthedMaintenanceRecordsIndexRoute
  '/_authed/assets/$id/edit': typeof AuthedAssetsIdEditRoute
  '/_authed/maintenance-records/$id/edit': typeof AuthedMaintenanceRecordsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/maintenance-records'
    | '/dashboard'
    | '/assets/live'
    | '/assets/new'
    | '/maintenance-records/new'
    | '/assets/'
    | '/maintenance-records/'
    | '/assets/$id/edit'
    | '/maintenance-records/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/assets/live'
    | '/assets/new'
    | '/maintenance-records/new'
    | '/assets'
    | '/maintenance-records'
    | '/assets/$id/edit'
    | '/maintenance-records/$id/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/maintenance-records'
    | '/_authed/dashboard'
    | '/_authed/'
    | '/_authed/assets/live'
    | '/_authed/assets/new'
    | '/_authed/maintenance-records/new'
    | '/_authed/assets/'
    | '/_authed/maintenance-records/'
    | '/_authed/assets/$id/edit'
    | '/_authed/maintenance-records/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance-records': {
      id: '/_authed/maintenance-records'
      path: '/maintenance-records'
      fullPath: '/maintenance-records'
      preLoaderRoute: typeof AuthedMaintenanceRecordsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/': {
      id: '/_authed/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthedAssetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/live': {
      id: '/_authed/assets/live'
      path: '/assets/live'
      fullPath: '/assets/live'
      preLoaderRoute: typeof AuthedAssetsLiveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/new': {
      id: '/_authed/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AuthedAssetsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance-records/': {
      id: '/_authed/maintenance-records/'
      path: '/'
      fullPath: '/maintenance-records/'
      preLoaderRoute: typeof AuthedMaintenanceRecordsIndexRouteImport
      parentRoute: typeof AuthedMaintenanceRecordsRouteRoute
    }
    '/_authed/maintenance-records/new': {
      id: '/_authed/maintenance-records/new'
      path: '/new'
      fullPath: '/maintenance-records/new'
      preLoaderRoute: typeof AuthedMaintenanceRecordsNewRouteImport
      parentRoute: typeof AuthedMaintenanceRecordsRouteRoute
    }
    '/_authed/assets/$id/edit': {
      id: '/_authed/assets/$id/edit'
      path: '/assets/$id/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AuthedAssetsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance-records/$id/edit': {
      id: '/_authed/maintenance-records/$id/edit'
      path: '/$id/edit'
      fullPath: '/maintenance-records/$id/edit'
      preLoaderRoute: typeof AuthedMaintenanceRecordsIdEditRouteImport
      parentRoute: typeof AuthedMaintenanceRecordsRouteRoute
    }
  }
}

interface AuthedMaintenanceRecordsRouteRouteChildren {
  AuthedMaintenanceRecordsNewRoute: typeof AuthedMaintenanceRecordsNewRoute
  AuthedMaintenanceRecordsIndexRoute: typeof AuthedMaintenanceRecordsIndexRoute
  AuthedMaintenanceRecordsIdEditRoute: typeof AuthedMaintenanceRecordsIdEditRoute
}

const AuthedMaintenanceRecordsRouteRouteChildren: AuthedMaintenanceRecordsRouteRouteChildren =
  {
    AuthedMaintenanceRecordsNewRoute: AuthedMaintenanceRecordsNewRoute,
    AuthedMaintenanceRecordsIndexRoute: AuthedMaintenanceRecordsIndexRoute,
    AuthedMaintenanceRecordsIdEditRoute: AuthedMaintenanceRecordsIdEditRoute,
  }

const AuthedMaintenanceRecordsRouteRouteWithChildren =
  AuthedMaintenanceRecordsRouteRoute._addFileChildren(
    AuthedMaintenanceRecordsRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedMaintenanceRecordsRouteRoute: typeof AuthedMaintenanceRecordsRouteRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAssetsLiveRoute: typeof AuthedAssetsLiveRoute
  AuthedAssetsNewRoute: typeof AuthedAssetsNewRoute
  AuthedAssetsIndexRoute: typeof AuthedAssetsIndexRoute
  AuthedAssetsIdEditRoute: typeof AuthedAssetsIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMaintenanceRecordsRouteRoute:
    AuthedMaintenanceRecordsRouteRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAssetsLiveRoute: AuthedAssetsLiveRoute,
  AuthedAssetsNewRoute: AuthedAssetsNewRoute,
  AuthedAssetsIndexRoute: AuthedAssetsIndexRoute,
  AuthedAssetsIdEditRoute: AuthedAssetsIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
