/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaintenanceRecordsIndexRouteImport } from './routes/maintenance-records/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRecordsIndexRoute = MaintenanceRecordsIndexRouteImport.update({
  id: '/maintenance-records/',
  path: '/maintenance-records/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintenance-records/': typeof MaintenanceRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance-records': typeof MaintenanceRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintenance-records/': typeof MaintenanceRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maintenance-records/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maintenance-records'
  id: '__root__' | '/' | '/maintenance-records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintenanceRecordsIndexRoute: typeof MaintenanceRecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-records/': {
      id: '/maintenance-records/'
      path: '/maintenance-records'
      fullPath: '/maintenance-records/'
      preLoaderRoute: typeof MaintenanceRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintenanceRecordsIndexRoute: MaintenanceRecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
